

SELECT * FROM [dbo].[Features]

SELECT * FROM [dbo].[Features] 

CREATE TABLE #FEATURES_2(STORE INT,DATE DATE,TEMPERATURE DECIMAL(5,2),FULE_PRISE DECIMAL(5,2))

5

SELECT * FROM #FEATURES_2

DROP TABLE #FEATURES_2

SELECT * FROM #FEATURES

SELECT * FROM #FEATURES AS F1
INNER JOIN #FEATURES_2 AS F2
ON F1.FULE_PRISE=F2.FULE_PRISE

CREATE TABLE #AVG_F(STORE INT, AVG_TEMP DECIMAL(18,2),AVG_FUEL_P DECIMAL(18,2),AVG_UNEMP dECIMAL(18,2))

INSERT INTO #AVG_F(STORE ,AVG_TEMP,AVG_FUEL_P,AVG_UNEMP)
SELECT STORE,aVG(Temperature),AVG(Fuel_Price),AVG(Unemployment) FROM [dbo].[Features] GROUP BY Store 

DROP TABLE #AVG_F

SELECT * FROM #AVG_F

SELECT * FROM #FEATURES AS F1
INNER JOIN #AVG_F AS F2
ON F1.STORE=F2.STORE